package registry

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	goplugin "github.com/hashicorp/go-plugin"

	"github.com/charlesng35/shellcn/sdk/gen/pluginv1"
	"github.com/charlesng35/shellcn/sdk/grpcplugin"
	"github.com/charlesng35/shellcn/sdk/plugin"
)

const (
	SandboxNone  = "none"
	SandboxBasic = "basic"
)

// Snapshot is what inspection captures from a verified binary: everything the
// gateway needs to present the plugin before install. Generated by CI, stored
// under snapshots/, and embedded into index.json.
type Snapshot struct {
	Name            string          `json:"name"`
	Version         string          `json:"version"`
	APIVersion      int             `json:"apiVersion"`
	ProtocolVersion int             `json:"protocolVersion"`
	Icon            plugin.Icon     `json:"icon"`
	Projection      json.RawMessage `json:"projection"`
	Inspection      Inspection      `json:"inspection,omitempty"`
}

// Inspection records how the binary was executed to capture the snapshot.
type Inspection struct {
	Sandbox string `json:"sandbox,omitempty"`
}

// Expect pins what a verified binary must present; empty fields are unchecked.
type Expect struct {
	Name    string
	Version string
}

// InspectOptions controls binary inspection.
type InspectOptions struct {
	Expect  Expect
	Sandbox string
}

// check fails when the binary's identity diverges from the registry manifest:
// the index must never describe one plugin and install another.
func (s *Snapshot) check(want Expect) error {
	var errs []string
	if want.Name != "" && s.Name != want.Name {
		errs = append(errs, fmt.Sprintf("binary presents plugin name %q, manifest says %q", s.Name, want.Name))
	}
	if want.Version != "" && s.Version != want.Version {
		errs = append(errs, fmt.Sprintf("binary presents version %q, manifest entry is %q", s.Version, want.Version))
	}
	if len(errs) > 0 {
		return fmt.Errorf("%s", strings.Join(errs, "; "))
	}
	return nil
}

// Inspect runs a plugin binary through the real go-plugin handshake, fetches
// its manifest, validates it exactly as the gateway would, checks it against
// want, and returns the snapshot. The subprocess is killed before returning.
func Inspect(binary string, want Expect) (*Snapshot, error) {
	return InspectWithOptions(binary, InspectOptions{Expect: want})
}

// InspectWithOptions runs a plugin binary through the real go-plugin handshake,
// fetches its manifest, validates it exactly as the gateway would, checks it
// against want, and returns the snapshot. The subprocess is killed before
// returning.
func InspectWithOptions(binary string, opts InspectOptions) (*Snapshot, error) {
	cmd, cleanup, err := inspectCommand(binary, opts.Sandbox)
	if err != nil {
		return nil, err
	}
	defer cleanup()
	client := goplugin.NewClient(&goplugin.ClientConfig{
		HandshakeConfig:  grpcplugin.Handshake,
		Plugins:          grpcplugin.Plugins(nil),
		Cmd:              cmd,
		AllowedProtocols: []goplugin.Protocol{goplugin.ProtocolGRPC},
		AutoMTLS:         true,
		SkipHostEnv:      true,
		StartTimeout:     30 * time.Second,
	})
	defer client.Kill()

	rpc, err := client.Client()
	if err != nil {
		return nil, fmt.Errorf("handshake: %w", err)
	}
	dispensed, err := rpc.Dispense(grpcplugin.PluginName)
	if err != nil {
		return nil, fmt.Errorf("dispense: %w", err)
	}
	pc, ok := dispensed.(*grpcplugin.Client)
	if !ok {
		return nil, fmt.Errorf("unexpected dispense type %T", dispensed)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	resp, err := pc.Plugin.GetManifest(ctx, &pluginv1.Empty{})
	if err != nil {
		return nil, fmt.Errorf("GetManifest: %w", err)
	}
	manifest, routes, err := grpcplugin.DecodeManifest(resp.GetJson())
	if err != nil {
		return nil, fmt.Errorf("decode manifest: %w", err)
	}
	// Decoded routes carry no handler funcs (they are gRPC shims host-side); the
	// gateway binds shims before validating, so the inspector does the same.
	for i := range routes {
		if routes[i].IsStream() {
			routes[i].Stream = func(*plugin.RequestContext, plugin.ClientStream) error { return nil }
		} else {
			routes[i].Handle = func(*plugin.RequestContext) (any, error) { return nil, nil }
		}
	}
	if err := plugin.Validate(manifest, routes); err != nil {
		return nil, fmt.Errorf("manifest validation: %w", err)
	}

	icon, err := NormalizeIcon(manifest.Icon)
	if err != nil {
		return nil, fmt.Errorf("icon: %w", err)
	}

	byID := make(map[string]plugin.Route, len(routes))
	for _, r := range routes {
		byID[r.ID] = r
	}
	projection, err := json.Marshal(plugin.BuildProjection(manifest, byID))
	if err != nil {
		return nil, fmt.Errorf("projection: %w", err)
	}
	snap := &Snapshot{
		Name:            manifest.Name,
		Version:         manifest.Version,
		APIVersion:      manifest.APIVersion,
		ProtocolVersion: grpcplugin.ProtocolVersion,
		Icon:            icon,
		Projection:      projection,
		Inspection:      Inspection{Sandbox: normalizeSandbox(opts.Sandbox)},
	}
	if err := snap.check(opts.Expect); err != nil {
		return nil, err
	}
	return snap, nil
}

func inspectCommand(binary, sandbox string) (*exec.Cmd, func(), error) {
	mode := normalizeSandbox(sandbox)
	abs, err := filepath.Abs(binary)
	if err != nil {
		return nil, func() {}, err
	}
	if mode == SandboxNone {
		cmd := exec.Command(abs)
		return cmd, func() {}, nil
	}
	dir, err := os.MkdirTemp("", "regctl-plugin-sandbox-*")
	if err != nil {
		return nil, func() {}, err
	}
	cleanup := func() { _ = os.RemoveAll(dir) }
	cmd := exec.Command(abs)
	cmd.Dir = dir
	cmd.Env = []string{
		"HOME=" + dir,
		"TMPDIR=" + dir,
		"TEMP=" + dir,
		"TMP=" + dir,
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"SHELL=/bin/sh",
		"USER=shellcn-registry",
	}
	if runtime.GOOS == "windows" {
		cmd.Env = append(cmd.Env, "SystemRoot="+os.Getenv("SystemRoot"))
	}
	return cmd, cleanup, nil
}

func normalizeSandbox(mode string) string {
	switch strings.ToLower(strings.TrimSpace(mode)) {
	case "", SandboxNone:
		return SandboxNone
	case SandboxBasic, "true", "1", "yes":
		return SandboxBasic
	default:
		return mode
	}
}
