package registry

import (
	"context"
	"fmt"
	"os/exec"
	"time"

	goplugin "github.com/hashicorp/go-plugin"

	"github.com/charlesng35/shellcn/sdk/gen/pluginv1"
	"github.com/charlesng35/shellcn/sdk/grpcplugin"
	"github.com/charlesng35/shellcn/sdk/plugin"
)

// Snapshot is what inspection captures from a verified binary: everything the
// gateway needs to present the plugin before install. Generated by CI, stored
// under snapshots/, and embedded into index.json.
type Snapshot struct {
	Name            string            `json:"name"`
	Version         string            `json:"version"`
	APIVersion      int               `json:"apiVersion"`
	ProtocolVersion int               `json:"protocolVersion"`
	Icon            plugin.Icon       `json:"icon"`
	Projection      plugin.Projection `json:"projection"`
}

// Inspect runs a plugin binary through the real go-plugin handshake, fetches
// its manifest, validates it exactly as the gateway would, and returns the
// snapshot. The subprocess is killed before returning.
func Inspect(binary string) (*Snapshot, error) {
	client := goplugin.NewClient(&goplugin.ClientConfig{
		HandshakeConfig:  grpcplugin.Handshake,
		Plugins:          grpcplugin.Plugins(nil),
		Cmd:              exec.Command(binary),
		AllowedProtocols: []goplugin.Protocol{goplugin.ProtocolGRPC},
		AutoMTLS:         true,
		StartTimeout:     30 * time.Second,
	})
	defer client.Kill()

	rpc, err := client.Client()
	if err != nil {
		return nil, fmt.Errorf("handshake: %w", err)
	}
	dispensed, err := rpc.Dispense(grpcplugin.PluginName)
	if err != nil {
		return nil, fmt.Errorf("dispense: %w", err)
	}
	pc, ok := dispensed.(*grpcplugin.Client)
	if !ok {
		return nil, fmt.Errorf("unexpected dispense type %T", dispensed)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	resp, err := pc.Plugin.GetManifest(ctx, &pluginv1.Empty{})
	if err != nil {
		return nil, fmt.Errorf("GetManifest: %w", err)
	}
	manifest, routes, err := grpcplugin.DecodeManifest(resp.GetJson())
	if err != nil {
		return nil, fmt.Errorf("decode manifest: %w", err)
	}
	// Decoded routes carry no handler funcs (they are gRPC shims host-side); the
	// gateway binds shims before validating, so the inspector does the same.
	for i := range routes {
		if routes[i].IsStream() {
			routes[i].Stream = func(*plugin.RequestContext, plugin.ClientStream) error { return nil }
		} else {
			routes[i].Handle = func(*plugin.RequestContext) (any, error) { return nil, nil }
		}
	}
	if err := plugin.Validate(manifest, routes); err != nil {
		return nil, fmt.Errorf("manifest validation: %w", err)
	}

	icon, err := NormalizeIcon(manifest.Icon)
	if err != nil {
		return nil, fmt.Errorf("icon: %w", err)
	}

	byID := make(map[string]plugin.Route, len(routes))
	for _, r := range routes {
		byID[r.ID] = r
	}
	return &Snapshot{
		Name:            manifest.Name,
		Version:         manifest.Version,
		APIVersion:      manifest.APIVersion,
		ProtocolVersion: grpcplugin.ProtocolVersion,
		Icon:            icon,
		Projection:      plugin.BuildProjection(manifest, byID),
	}, nil
}
